---
language: python
services:
  - docker

before_install:
  - sudo pip install yamllint -qqq
  - sudo apt-get install --only-upgrade docker
  - sudo apt-get install --only-upgrade docker-compose

script:
  - yamllint -c .lint.yml docker-compose.yml
  - cp example.env .env
  - docker-compose config --services

notifications:
  email: false

git:
  quiet: true
